/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OrganizationRouteImport } from './routes/organization'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrganizationIndexRouteImport } from './routes/organization/index'
import { Route as OrganizationSubscriptionRouteImport } from './routes/organization/subscription'
import { Route as OrganizationRenderRouteImport } from './routes/organization/render'
import { Route as OrganizationLoginRouteImport } from './routes/organization/login'
import { Route as OrganizationDashboardRouteImport } from './routes/organization/dashboard'
import { Route as OrganizationDashboardIndexRouteImport } from './routes/organization/dashboard/index'
import { Route as OrganizationDashboardSettingsRouteImport } from './routes/organization/dashboard/settings'
import { Route as OrganizationDashboardRevenueRouteImport } from './routes/organization/dashboard/revenue'
import { Route as OrganizationDashboardPublishRouteImport } from './routes/organization/dashboard/publish'
import { Route as OrganizationDashboardOverviewRouteImport } from './routes/organization/dashboard/overview'
import { Route as OrganizationDashboardNewspapersRouteImport } from './routes/organization/dashboard/newspapers'

const OrganizationRoute = OrganizationRouteImport.update({
  id: '/organization',
  path: '/organization',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationIndexRoute = OrganizationIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrganizationRoute,
} as any)
const OrganizationSubscriptionRoute =
  OrganizationSubscriptionRouteImport.update({
    id: '/subscription',
    path: '/subscription',
    getParentRoute: () => OrganizationRoute,
  } as any)
const OrganizationRenderRoute = OrganizationRenderRouteImport.update({
  id: '/render',
  path: '/render',
  getParentRoute: () => OrganizationRoute,
} as any)
const OrganizationLoginRoute = OrganizationLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => OrganizationRoute,
} as any)
const OrganizationDashboardRoute = OrganizationDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => OrganizationRoute,
} as any)
const OrganizationDashboardIndexRoute =
  OrganizationDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => OrganizationDashboardRoute,
  } as any)
const OrganizationDashboardSettingsRoute =
  OrganizationDashboardSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => OrganizationDashboardRoute,
  } as any)
const OrganizationDashboardRevenueRoute =
  OrganizationDashboardRevenueRouteImport.update({
    id: '/revenue',
    path: '/revenue',
    getParentRoute: () => OrganizationDashboardRoute,
  } as any)
const OrganizationDashboardPublishRoute =
  OrganizationDashboardPublishRouteImport.update({
    id: '/publish',
    path: '/publish',
    getParentRoute: () => OrganizationDashboardRoute,
  } as any)
const OrganizationDashboardOverviewRoute =
  OrganizationDashboardOverviewRouteImport.update({
    id: '/overview',
    path: '/overview',
    getParentRoute: () => OrganizationDashboardRoute,
  } as any)
const OrganizationDashboardNewspapersRoute =
  OrganizationDashboardNewspapersRouteImport.update({
    id: '/newspapers',
    path: '/newspapers',
    getParentRoute: () => OrganizationDashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/organization': typeof OrganizationRouteWithChildren
  '/organization/dashboard': typeof OrganizationDashboardRouteWithChildren
  '/organization/login': typeof OrganizationLoginRoute
  '/organization/render': typeof OrganizationRenderRoute
  '/organization/subscription': typeof OrganizationSubscriptionRoute
  '/organization/': typeof OrganizationIndexRoute
  '/organization/dashboard/newspapers': typeof OrganizationDashboardNewspapersRoute
  '/organization/dashboard/overview': typeof OrganizationDashboardOverviewRoute
  '/organization/dashboard/publish': typeof OrganizationDashboardPublishRoute
  '/organization/dashboard/revenue': typeof OrganizationDashboardRevenueRoute
  '/organization/dashboard/settings': typeof OrganizationDashboardSettingsRoute
  '/organization/dashboard/': typeof OrganizationDashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/organization/login': typeof OrganizationLoginRoute
  '/organization/render': typeof OrganizationRenderRoute
  '/organization/subscription': typeof OrganizationSubscriptionRoute
  '/organization': typeof OrganizationIndexRoute
  '/organization/dashboard/newspapers': typeof OrganizationDashboardNewspapersRoute
  '/organization/dashboard/overview': typeof OrganizationDashboardOverviewRoute
  '/organization/dashboard/publish': typeof OrganizationDashboardPublishRoute
  '/organization/dashboard/revenue': typeof OrganizationDashboardRevenueRoute
  '/organization/dashboard/settings': typeof OrganizationDashboardSettingsRoute
  '/organization/dashboard': typeof OrganizationDashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/organization': typeof OrganizationRouteWithChildren
  '/organization/dashboard': typeof OrganizationDashboardRouteWithChildren
  '/organization/login': typeof OrganizationLoginRoute
  '/organization/render': typeof OrganizationRenderRoute
  '/organization/subscription': typeof OrganizationSubscriptionRoute
  '/organization/': typeof OrganizationIndexRoute
  '/organization/dashboard/newspapers': typeof OrganizationDashboardNewspapersRoute
  '/organization/dashboard/overview': typeof OrganizationDashboardOverviewRoute
  '/organization/dashboard/publish': typeof OrganizationDashboardPublishRoute
  '/organization/dashboard/revenue': typeof OrganizationDashboardRevenueRoute
  '/organization/dashboard/settings': typeof OrganizationDashboardSettingsRoute
  '/organization/dashboard/': typeof OrganizationDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/organization'
    | '/organization/dashboard'
    | '/organization/login'
    | '/organization/render'
    | '/organization/subscription'
    | '/organization/'
    | '/organization/dashboard/newspapers'
    | '/organization/dashboard/overview'
    | '/organization/dashboard/publish'
    | '/organization/dashboard/revenue'
    | '/organization/dashboard/settings'
    | '/organization/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/organization/login'
    | '/organization/render'
    | '/organization/subscription'
    | '/organization'
    | '/organization/dashboard/newspapers'
    | '/organization/dashboard/overview'
    | '/organization/dashboard/publish'
    | '/organization/dashboard/revenue'
    | '/organization/dashboard/settings'
    | '/organization/dashboard'
  id:
    | '__root__'
    | '/'
    | '/organization'
    | '/organization/dashboard'
    | '/organization/login'
    | '/organization/render'
    | '/organization/subscription'
    | '/organization/'
    | '/organization/dashboard/newspapers'
    | '/organization/dashboard/overview'
    | '/organization/dashboard/publish'
    | '/organization/dashboard/revenue'
    | '/organization/dashboard/settings'
    | '/organization/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OrganizationRoute: typeof OrganizationRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/organization': {
      id: '/organization'
      path: '/organization'
      fullPath: '/organization'
      preLoaderRoute: typeof OrganizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organization/': {
      id: '/organization/'
      path: '/'
      fullPath: '/organization/'
      preLoaderRoute: typeof OrganizationIndexRouteImport
      parentRoute: typeof OrganizationRoute
    }
    '/organization/subscription': {
      id: '/organization/subscription'
      path: '/subscription'
      fullPath: '/organization/subscription'
      preLoaderRoute: typeof OrganizationSubscriptionRouteImport
      parentRoute: typeof OrganizationRoute
    }
    '/organization/render': {
      id: '/organization/render'
      path: '/render'
      fullPath: '/organization/render'
      preLoaderRoute: typeof OrganizationRenderRouteImport
      parentRoute: typeof OrganizationRoute
    }
    '/organization/login': {
      id: '/organization/login'
      path: '/login'
      fullPath: '/organization/login'
      preLoaderRoute: typeof OrganizationLoginRouteImport
      parentRoute: typeof OrganizationRoute
    }
    '/organization/dashboard': {
      id: '/organization/dashboard'
      path: '/dashboard'
      fullPath: '/organization/dashboard'
      preLoaderRoute: typeof OrganizationDashboardRouteImport
      parentRoute: typeof OrganizationRoute
    }
    '/organization/dashboard/': {
      id: '/organization/dashboard/'
      path: '/'
      fullPath: '/organization/dashboard/'
      preLoaderRoute: typeof OrganizationDashboardIndexRouteImport
      parentRoute: typeof OrganizationDashboardRoute
    }
    '/organization/dashboard/settings': {
      id: '/organization/dashboard/settings'
      path: '/settings'
      fullPath: '/organization/dashboard/settings'
      preLoaderRoute: typeof OrganizationDashboardSettingsRouteImport
      parentRoute: typeof OrganizationDashboardRoute
    }
    '/organization/dashboard/revenue': {
      id: '/organization/dashboard/revenue'
      path: '/revenue'
      fullPath: '/organization/dashboard/revenue'
      preLoaderRoute: typeof OrganizationDashboardRevenueRouteImport
      parentRoute: typeof OrganizationDashboardRoute
    }
    '/organization/dashboard/publish': {
      id: '/organization/dashboard/publish'
      path: '/publish'
      fullPath: '/organization/dashboard/publish'
      preLoaderRoute: typeof OrganizationDashboardPublishRouteImport
      parentRoute: typeof OrganizationDashboardRoute
    }
    '/organization/dashboard/overview': {
      id: '/organization/dashboard/overview'
      path: '/overview'
      fullPath: '/organization/dashboard/overview'
      preLoaderRoute: typeof OrganizationDashboardOverviewRouteImport
      parentRoute: typeof OrganizationDashboardRoute
    }
    '/organization/dashboard/newspapers': {
      id: '/organization/dashboard/newspapers'
      path: '/newspapers'
      fullPath: '/organization/dashboard/newspapers'
      preLoaderRoute: typeof OrganizationDashboardNewspapersRouteImport
      parentRoute: typeof OrganizationDashboardRoute
    }
  }
}

interface OrganizationDashboardRouteChildren {
  OrganizationDashboardNewspapersRoute: typeof OrganizationDashboardNewspapersRoute
  OrganizationDashboardOverviewRoute: typeof OrganizationDashboardOverviewRoute
  OrganizationDashboardPublishRoute: typeof OrganizationDashboardPublishRoute
  OrganizationDashboardRevenueRoute: typeof OrganizationDashboardRevenueRoute
  OrganizationDashboardSettingsRoute: typeof OrganizationDashboardSettingsRoute
  OrganizationDashboardIndexRoute: typeof OrganizationDashboardIndexRoute
}

const OrganizationDashboardRouteChildren: OrganizationDashboardRouteChildren = {
  OrganizationDashboardNewspapersRoute: OrganizationDashboardNewspapersRoute,
  OrganizationDashboardOverviewRoute: OrganizationDashboardOverviewRoute,
  OrganizationDashboardPublishRoute: OrganizationDashboardPublishRoute,
  OrganizationDashboardRevenueRoute: OrganizationDashboardRevenueRoute,
  OrganizationDashboardSettingsRoute: OrganizationDashboardSettingsRoute,
  OrganizationDashboardIndexRoute: OrganizationDashboardIndexRoute,
}

const OrganizationDashboardRouteWithChildren =
  OrganizationDashboardRoute._addFileChildren(
    OrganizationDashboardRouteChildren,
  )

interface OrganizationRouteChildren {
  OrganizationDashboardRoute: typeof OrganizationDashboardRouteWithChildren
  OrganizationLoginRoute: typeof OrganizationLoginRoute
  OrganizationRenderRoute: typeof OrganizationRenderRoute
  OrganizationSubscriptionRoute: typeof OrganizationSubscriptionRoute
  OrganizationIndexRoute: typeof OrganizationIndexRoute
}

const OrganizationRouteChildren: OrganizationRouteChildren = {
  OrganizationDashboardRoute: OrganizationDashboardRouteWithChildren,
  OrganizationLoginRoute: OrganizationLoginRoute,
  OrganizationRenderRoute: OrganizationRenderRoute,
  OrganizationSubscriptionRoute: OrganizationSubscriptionRoute,
  OrganizationIndexRoute: OrganizationIndexRoute,
}

const OrganizationRouteWithChildren = OrganizationRoute._addFileChildren(
  OrganizationRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OrganizationRoute: OrganizationRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
