/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SupportRouteImport } from './routes/support'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PartnershipRouteImport } from './routes/partnership'
import { Route as OrganizationRouteImport } from './routes/organization'
import { Route as NewspapersRouteImport } from './routes/newspapers'
import { Route as MagazinesRouteImport } from './routes/magazines'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CountriesRouteImport } from './routes/countries'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConfidentialiteRouteImport } from './routes/confidentialite'
import { Route as CgvRouteImport } from './routes/cgv'
import { Route as CgcRouteImport } from './routes/cgc'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrganizationIndexRouteImport } from './routes/organization/index'
import { Route as NewspapersIndexRouteImport } from './routes/newspapers/index'
import { Route as MagazinesIndexRouteImport } from './routes/magazines/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as AgenciesIndexRouteImport } from './routes/agencies/index'
import { Route as PaymentSuccessRouteImport } from './routes/payment/success'
import { Route as OrganizationSubscriptionRouteImport } from './routes/organization/subscription'
import { Route as OrganizationLoginRouteImport } from './routes/organization/login'
import { Route as NewspapersNewspaperIdRouteImport } from './routes/newspapers/$newspaperId'
import { Route as MagazinesMagazineIdRouteImport } from './routes/magazines/$magazineId'
import { Route as DashboardProfilRouteImport } from './routes/dashboard/profil'
import { Route as DashboardParametresRouteImport } from './routes/dashboard/parametres'
import { Route as DashboardFavorisRouteImport } from './routes/dashboard/favoris'
import { Route as DashboardAchatsRouteImport } from './routes/dashboard/achats'
import { Route as CountriesCountrySlugRouteImport } from './routes/countries/$countrySlug'
import { Route as CategoriesCategorySlugRouteImport } from './routes/categories/$categorySlug'
import { Route as AgenciesAgencySlugRouteImport } from './routes/agencies/$agencySlug'
import { Route as NewspapersNewspaperIdIndexRouteImport } from './routes/newspapers/$newspaperId/index'
import { Route as MagazinesMagazineIdIndexRouteImport } from './routes/magazines/$magazineId/index'
import { Route as NewspapersNewspaperIdRenderRouteImport } from './routes/newspapers/$newspaperId/render'
import { Route as MagazinesMagazineIdRenderRouteImport } from './routes/magazines/$magazineId/render'

const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnershipRoute = PartnershipRouteImport.update({
  id: '/partnership',
  path: '/partnership',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationRoute = OrganizationRouteImport.update({
  id: '/organization',
  path: '/organization',
  getParentRoute: () => rootRouteImport,
} as any)
const NewspapersRoute = NewspapersRouteImport.update({
  id: '/newspapers',
  path: '/newspapers',
  getParentRoute: () => rootRouteImport,
} as any)
const MagazinesRoute = MagazinesRouteImport.update({
  id: '/magazines',
  path: '/magazines',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CountriesRoute = CountriesRouteImport.update({
  id: '/countries',
  path: '/countries',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfidentialiteRoute = ConfidentialiteRouteImport.update({
  id: '/confidentialite',
  path: '/confidentialite',
  getParentRoute: () => rootRouteImport,
} as any)
const CgvRoute = CgvRouteImport.update({
  id: '/cgv',
  path: '/cgv',
  getParentRoute: () => rootRouteImport,
} as any)
const CgcRoute = CgcRouteImport.update({
  id: '/cgc',
  path: '/cgc',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationIndexRoute = OrganizationIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrganizationRoute,
} as any)
const NewspapersIndexRoute = NewspapersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NewspapersRoute,
} as any)
const MagazinesIndexRoute = MagazinesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MagazinesRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const AgenciesIndexRoute = AgenciesIndexRouteImport.update({
  id: '/agencies/',
  path: '/agencies/',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentSuccessRoute = PaymentSuccessRouteImport.update({
  id: '/payment/success',
  path: '/payment/success',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationSubscriptionRoute =
  OrganizationSubscriptionRouteImport.update({
    id: '/subscription',
    path: '/subscription',
    getParentRoute: () => OrganizationRoute,
  } as any)
const OrganizationLoginRoute = OrganizationLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => OrganizationRoute,
} as any)
const NewspapersNewspaperIdRoute = NewspapersNewspaperIdRouteImport.update({
  id: '/$newspaperId',
  path: '/$newspaperId',
  getParentRoute: () => NewspapersRoute,
} as any)
const MagazinesMagazineIdRoute = MagazinesMagazineIdRouteImport.update({
  id: '/$magazineId',
  path: '/$magazineId',
  getParentRoute: () => MagazinesRoute,
} as any)
const DashboardProfilRoute = DashboardProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardParametresRoute = DashboardParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFavorisRoute = DashboardFavorisRouteImport.update({
  id: '/favoris',
  path: '/favoris',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAchatsRoute = DashboardAchatsRouteImport.update({
  id: '/achats',
  path: '/achats',
  getParentRoute: () => DashboardRoute,
} as any)
const CountriesCountrySlugRoute = CountriesCountrySlugRouteImport.update({
  id: '/$countrySlug',
  path: '/$countrySlug',
  getParentRoute: () => CountriesRoute,
} as any)
const CategoriesCategorySlugRoute = CategoriesCategorySlugRouteImport.update({
  id: '/$categorySlug',
  path: '/$categorySlug',
  getParentRoute: () => CategoriesRoute,
} as any)
const AgenciesAgencySlugRoute = AgenciesAgencySlugRouteImport.update({
  id: '/agencies/$agencySlug',
  path: '/agencies/$agencySlug',
  getParentRoute: () => rootRouteImport,
} as any)
const NewspapersNewspaperIdIndexRoute =
  NewspapersNewspaperIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => NewspapersNewspaperIdRoute,
  } as any)
const MagazinesMagazineIdIndexRoute =
  MagazinesMagazineIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => MagazinesMagazineIdRoute,
  } as any)
const NewspapersNewspaperIdRenderRoute =
  NewspapersNewspaperIdRenderRouteImport.update({
    id: '/render',
    path: '/render',
    getParentRoute: () => NewspapersNewspaperIdRoute,
  } as any)
const MagazinesMagazineIdRenderRoute =
  MagazinesMagazineIdRenderRouteImport.update({
    id: '/render',
    path: '/render',
    getParentRoute: () => MagazinesMagazineIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRouteWithChildren
  '/cgc': typeof CgcRoute
  '/cgv': typeof CgvRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/contact': typeof ContactRoute
  '/countries': typeof CountriesRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/magazines': typeof MagazinesRouteWithChildren
  '/newspapers': typeof NewspapersRouteWithChildren
  '/organization': typeof OrganizationRouteWithChildren
  '/partnership': typeof PartnershipRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/support': typeof SupportRoute
  '/agencies/$agencySlug': typeof AgenciesAgencySlugRoute
  '/categories/$categorySlug': typeof CategoriesCategorySlugRoute
  '/countries/$countrySlug': typeof CountriesCountrySlugRoute
  '/dashboard/achats': typeof DashboardAchatsRoute
  '/dashboard/favoris': typeof DashboardFavorisRoute
  '/dashboard/parametres': typeof DashboardParametresRoute
  '/dashboard/profil': typeof DashboardProfilRoute
  '/magazines/$magazineId': typeof MagazinesMagazineIdRouteWithChildren
  '/newspapers/$newspaperId': typeof NewspapersNewspaperIdRouteWithChildren
  '/organization/login': typeof OrganizationLoginRoute
  '/organization/subscription': typeof OrganizationSubscriptionRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/agencies/': typeof AgenciesIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/magazines/': typeof MagazinesIndexRoute
  '/newspapers/': typeof NewspapersIndexRoute
  '/organization/': typeof OrganizationIndexRoute
  '/magazines/$magazineId/render': typeof MagazinesMagazineIdRenderRoute
  '/newspapers/$newspaperId/render': typeof NewspapersNewspaperIdRenderRoute
  '/magazines/$magazineId/': typeof MagazinesMagazineIdIndexRoute
  '/newspapers/$newspaperId/': typeof NewspapersNewspaperIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRouteWithChildren
  '/cgc': typeof CgcRoute
  '/cgv': typeof CgvRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/contact': typeof ContactRoute
  '/countries': typeof CountriesRouteWithChildren
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/partnership': typeof PartnershipRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/support': typeof SupportRoute
  '/agencies/$agencySlug': typeof AgenciesAgencySlugRoute
  '/categories/$categorySlug': typeof CategoriesCategorySlugRoute
  '/countries/$countrySlug': typeof CountriesCountrySlugRoute
  '/dashboard/achats': typeof DashboardAchatsRoute
  '/dashboard/favoris': typeof DashboardFavorisRoute
  '/dashboard/parametres': typeof DashboardParametresRoute
  '/dashboard/profil': typeof DashboardProfilRoute
  '/organization/login': typeof OrganizationLoginRoute
  '/organization/subscription': typeof OrganizationSubscriptionRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/agencies': typeof AgenciesIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/magazines': typeof MagazinesIndexRoute
  '/newspapers': typeof NewspapersIndexRoute
  '/organization': typeof OrganizationIndexRoute
  '/magazines/$magazineId/render': typeof MagazinesMagazineIdRenderRoute
  '/newspapers/$newspaperId/render': typeof NewspapersNewspaperIdRenderRoute
  '/magazines/$magazineId': typeof MagazinesMagazineIdIndexRoute
  '/newspapers/$newspaperId': typeof NewspapersNewspaperIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRouteWithChildren
  '/cgc': typeof CgcRoute
  '/cgv': typeof CgvRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/contact': typeof ContactRoute
  '/countries': typeof CountriesRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/magazines': typeof MagazinesRouteWithChildren
  '/newspapers': typeof NewspapersRouteWithChildren
  '/organization': typeof OrganizationRouteWithChildren
  '/partnership': typeof PartnershipRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/support': typeof SupportRoute
  '/agencies/$agencySlug': typeof AgenciesAgencySlugRoute
  '/categories/$categorySlug': typeof CategoriesCategorySlugRoute
  '/countries/$countrySlug': typeof CountriesCountrySlugRoute
  '/dashboard/achats': typeof DashboardAchatsRoute
  '/dashboard/favoris': typeof DashboardFavorisRoute
  '/dashboard/parametres': typeof DashboardParametresRoute
  '/dashboard/profil': typeof DashboardProfilRoute
  '/magazines/$magazineId': typeof MagazinesMagazineIdRouteWithChildren
  '/newspapers/$newspaperId': typeof NewspapersNewspaperIdRouteWithChildren
  '/organization/login': typeof OrganizationLoginRoute
  '/organization/subscription': typeof OrganizationSubscriptionRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/agencies/': typeof AgenciesIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/magazines/': typeof MagazinesIndexRoute
  '/newspapers/': typeof NewspapersIndexRoute
  '/organization/': typeof OrganizationIndexRoute
  '/magazines/$magazineId/render': typeof MagazinesMagazineIdRenderRoute
  '/newspapers/$newspaperId/render': typeof NewspapersNewspaperIdRenderRoute
  '/magazines/$magazineId/': typeof MagazinesMagazineIdIndexRoute
  '/newspapers/$newspaperId/': typeof NewspapersNewspaperIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/cart'
    | '/categories'
    | '/cgc'
    | '/cgv'
    | '/confidentialite'
    | '/contact'
    | '/countries'
    | '/dashboard'
    | '/faq'
    | '/forgot-password'
    | '/login'
    | '/magazines'
    | '/newspapers'
    | '/organization'
    | '/partnership'
    | '/register'
    | '/reset-password'
    | '/support'
    | '/agencies/$agencySlug'
    | '/categories/$categorySlug'
    | '/countries/$countrySlug'
    | '/dashboard/achats'
    | '/dashboard/favoris'
    | '/dashboard/parametres'
    | '/dashboard/profil'
    | '/magazines/$magazineId'
    | '/newspapers/$newspaperId'
    | '/organization/login'
    | '/organization/subscription'
    | '/payment/success'
    | '/agencies/'
    | '/dashboard/'
    | '/magazines/'
    | '/newspapers/'
    | '/organization/'
    | '/magazines/$magazineId/render'
    | '/newspapers/$newspaperId/render'
    | '/magazines/$magazineId/'
    | '/newspapers/$newspaperId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cart'
    | '/categories'
    | '/cgc'
    | '/cgv'
    | '/confidentialite'
    | '/contact'
    | '/countries'
    | '/faq'
    | '/forgot-password'
    | '/login'
    | '/partnership'
    | '/register'
    | '/reset-password'
    | '/support'
    | '/agencies/$agencySlug'
    | '/categories/$categorySlug'
    | '/countries/$countrySlug'
    | '/dashboard/achats'
    | '/dashboard/favoris'
    | '/dashboard/parametres'
    | '/dashboard/profil'
    | '/organization/login'
    | '/organization/subscription'
    | '/payment/success'
    | '/agencies'
    | '/dashboard'
    | '/magazines'
    | '/newspapers'
    | '/organization'
    | '/magazines/$magazineId/render'
    | '/newspapers/$newspaperId/render'
    | '/magazines/$magazineId'
    | '/newspapers/$newspaperId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/cart'
    | '/categories'
    | '/cgc'
    | '/cgv'
    | '/confidentialite'
    | '/contact'
    | '/countries'
    | '/dashboard'
    | '/faq'
    | '/forgot-password'
    | '/login'
    | '/magazines'
    | '/newspapers'
    | '/organization'
    | '/partnership'
    | '/register'
    | '/reset-password'
    | '/support'
    | '/agencies/$agencySlug'
    | '/categories/$categorySlug'
    | '/countries/$countrySlug'
    | '/dashboard/achats'
    | '/dashboard/favoris'
    | '/dashboard/parametres'
    | '/dashboard/profil'
    | '/magazines/$magazineId'
    | '/newspapers/$newspaperId'
    | '/organization/login'
    | '/organization/subscription'
    | '/payment/success'
    | '/agencies/'
    | '/dashboard/'
    | '/magazines/'
    | '/newspapers/'
    | '/organization/'
    | '/magazines/$magazineId/render'
    | '/newspapers/$newspaperId/render'
    | '/magazines/$magazineId/'
    | '/newspapers/$newspaperId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CartRoute: typeof CartRoute
  CategoriesRoute: typeof CategoriesRouteWithChildren
  CgcRoute: typeof CgcRoute
  CgvRoute: typeof CgvRoute
  ConfidentialiteRoute: typeof ConfidentialiteRoute
  ContactRoute: typeof ContactRoute
  CountriesRoute: typeof CountriesRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  FaqRoute: typeof FaqRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  MagazinesRoute: typeof MagazinesRouteWithChildren
  NewspapersRoute: typeof NewspapersRouteWithChildren
  OrganizationRoute: typeof OrganizationRouteWithChildren
  PartnershipRoute: typeof PartnershipRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SupportRoute: typeof SupportRoute
  AgenciesAgencySlugRoute: typeof AgenciesAgencySlugRoute
  PaymentSuccessRoute: typeof PaymentSuccessRoute
  AgenciesIndexRoute: typeof AgenciesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partnership': {
      id: '/partnership'
      path: '/partnership'
      fullPath: '/partnership'
      preLoaderRoute: typeof PartnershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organization': {
      id: '/organization'
      path: '/organization'
      fullPath: '/organization'
      preLoaderRoute: typeof OrganizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newspapers': {
      id: '/newspapers'
      path: '/newspapers'
      fullPath: '/newspapers'
      preLoaderRoute: typeof NewspapersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/magazines': {
      id: '/magazines'
      path: '/magazines'
      fullPath: '/magazines'
      preLoaderRoute: typeof MagazinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/countries': {
      id: '/countries'
      path: '/countries'
      fullPath: '/countries'
      preLoaderRoute: typeof CountriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confidentialite': {
      id: '/confidentialite'
      path: '/confidentialite'
      fullPath: '/confidentialite'
      preLoaderRoute: typeof ConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cgv': {
      id: '/cgv'
      path: '/cgv'
      fullPath: '/cgv'
      preLoaderRoute: typeof CgvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cgc': {
      id: '/cgc'
      path: '/cgc'
      fullPath: '/cgc'
      preLoaderRoute: typeof CgcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organization/': {
      id: '/organization/'
      path: '/'
      fullPath: '/organization/'
      preLoaderRoute: typeof OrganizationIndexRouteImport
      parentRoute: typeof OrganizationRoute
    }
    '/newspapers/': {
      id: '/newspapers/'
      path: '/'
      fullPath: '/newspapers/'
      preLoaderRoute: typeof NewspapersIndexRouteImport
      parentRoute: typeof NewspapersRoute
    }
    '/magazines/': {
      id: '/magazines/'
      path: '/'
      fullPath: '/magazines/'
      preLoaderRoute: typeof MagazinesIndexRouteImport
      parentRoute: typeof MagazinesRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/agencies/': {
      id: '/agencies/'
      path: '/agencies'
      fullPath: '/agencies/'
      preLoaderRoute: typeof AgenciesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/success': {
      id: '/payment/success'
      path: '/payment/success'
      fullPath: '/payment/success'
      preLoaderRoute: typeof PaymentSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organization/subscription': {
      id: '/organization/subscription'
      path: '/subscription'
      fullPath: '/organization/subscription'
      preLoaderRoute: typeof OrganizationSubscriptionRouteImport
      parentRoute: typeof OrganizationRoute
    }
    '/organization/login': {
      id: '/organization/login'
      path: '/login'
      fullPath: '/organization/login'
      preLoaderRoute: typeof OrganizationLoginRouteImport
      parentRoute: typeof OrganizationRoute
    }
    '/newspapers/$newspaperId': {
      id: '/newspapers/$newspaperId'
      path: '/$newspaperId'
      fullPath: '/newspapers/$newspaperId'
      preLoaderRoute: typeof NewspapersNewspaperIdRouteImport
      parentRoute: typeof NewspapersRoute
    }
    '/magazines/$magazineId': {
      id: '/magazines/$magazineId'
      path: '/$magazineId'
      fullPath: '/magazines/$magazineId'
      preLoaderRoute: typeof MagazinesMagazineIdRouteImport
      parentRoute: typeof MagazinesRoute
    }
    '/dashboard/profil': {
      id: '/dashboard/profil'
      path: '/profil'
      fullPath: '/dashboard/profil'
      preLoaderRoute: typeof DashboardProfilRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/parametres': {
      id: '/dashboard/parametres'
      path: '/parametres'
      fullPath: '/dashboard/parametres'
      preLoaderRoute: typeof DashboardParametresRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/favoris': {
      id: '/dashboard/favoris'
      path: '/favoris'
      fullPath: '/dashboard/favoris'
      preLoaderRoute: typeof DashboardFavorisRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/achats': {
      id: '/dashboard/achats'
      path: '/achats'
      fullPath: '/dashboard/achats'
      preLoaderRoute: typeof DashboardAchatsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/countries/$countrySlug': {
      id: '/countries/$countrySlug'
      path: '/$countrySlug'
      fullPath: '/countries/$countrySlug'
      preLoaderRoute: typeof CountriesCountrySlugRouteImport
      parentRoute: typeof CountriesRoute
    }
    '/categories/$categorySlug': {
      id: '/categories/$categorySlug'
      path: '/$categorySlug'
      fullPath: '/categories/$categorySlug'
      preLoaderRoute: typeof CategoriesCategorySlugRouteImport
      parentRoute: typeof CategoriesRoute
    }
    '/agencies/$agencySlug': {
      id: '/agencies/$agencySlug'
      path: '/agencies/$agencySlug'
      fullPath: '/agencies/$agencySlug'
      preLoaderRoute: typeof AgenciesAgencySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newspapers/$newspaperId/': {
      id: '/newspapers/$newspaperId/'
      path: '/'
      fullPath: '/newspapers/$newspaperId/'
      preLoaderRoute: typeof NewspapersNewspaperIdIndexRouteImport
      parentRoute: typeof NewspapersNewspaperIdRoute
    }
    '/magazines/$magazineId/': {
      id: '/magazines/$magazineId/'
      path: '/'
      fullPath: '/magazines/$magazineId/'
      preLoaderRoute: typeof MagazinesMagazineIdIndexRouteImport
      parentRoute: typeof MagazinesMagazineIdRoute
    }
    '/newspapers/$newspaperId/render': {
      id: '/newspapers/$newspaperId/render'
      path: '/render'
      fullPath: '/newspapers/$newspaperId/render'
      preLoaderRoute: typeof NewspapersNewspaperIdRenderRouteImport
      parentRoute: typeof NewspapersNewspaperIdRoute
    }
    '/magazines/$magazineId/render': {
      id: '/magazines/$magazineId/render'
      path: '/render'
      fullPath: '/magazines/$magazineId/render'
      preLoaderRoute: typeof MagazinesMagazineIdRenderRouteImport
      parentRoute: typeof MagazinesMagazineIdRoute
    }
  }
}

interface CategoriesRouteChildren {
  CategoriesCategorySlugRoute: typeof CategoriesCategorySlugRoute
}

const CategoriesRouteChildren: CategoriesRouteChildren = {
  CategoriesCategorySlugRoute: CategoriesCategorySlugRoute,
}

const CategoriesRouteWithChildren = CategoriesRoute._addFileChildren(
  CategoriesRouteChildren,
)

interface CountriesRouteChildren {
  CountriesCountrySlugRoute: typeof CountriesCountrySlugRoute
}

const CountriesRouteChildren: CountriesRouteChildren = {
  CountriesCountrySlugRoute: CountriesCountrySlugRoute,
}

const CountriesRouteWithChildren = CountriesRoute._addFileChildren(
  CountriesRouteChildren,
)

interface DashboardRouteChildren {
  DashboardAchatsRoute: typeof DashboardAchatsRoute
  DashboardFavorisRoute: typeof DashboardFavorisRoute
  DashboardParametresRoute: typeof DashboardParametresRoute
  DashboardProfilRoute: typeof DashboardProfilRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAchatsRoute: DashboardAchatsRoute,
  DashboardFavorisRoute: DashboardFavorisRoute,
  DashboardParametresRoute: DashboardParametresRoute,
  DashboardProfilRoute: DashboardProfilRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface MagazinesMagazineIdRouteChildren {
  MagazinesMagazineIdRenderRoute: typeof MagazinesMagazineIdRenderRoute
  MagazinesMagazineIdIndexRoute: typeof MagazinesMagazineIdIndexRoute
}

const MagazinesMagazineIdRouteChildren: MagazinesMagazineIdRouteChildren = {
  MagazinesMagazineIdRenderRoute: MagazinesMagazineIdRenderRoute,
  MagazinesMagazineIdIndexRoute: MagazinesMagazineIdIndexRoute,
}

const MagazinesMagazineIdRouteWithChildren =
  MagazinesMagazineIdRoute._addFileChildren(MagazinesMagazineIdRouteChildren)

interface MagazinesRouteChildren {
  MagazinesMagazineIdRoute: typeof MagazinesMagazineIdRouteWithChildren
  MagazinesIndexRoute: typeof MagazinesIndexRoute
}

const MagazinesRouteChildren: MagazinesRouteChildren = {
  MagazinesMagazineIdRoute: MagazinesMagazineIdRouteWithChildren,
  MagazinesIndexRoute: MagazinesIndexRoute,
}

const MagazinesRouteWithChildren = MagazinesRoute._addFileChildren(
  MagazinesRouteChildren,
)

interface NewspapersNewspaperIdRouteChildren {
  NewspapersNewspaperIdRenderRoute: typeof NewspapersNewspaperIdRenderRoute
  NewspapersNewspaperIdIndexRoute: typeof NewspapersNewspaperIdIndexRoute
}

const NewspapersNewspaperIdRouteChildren: NewspapersNewspaperIdRouteChildren = {
  NewspapersNewspaperIdRenderRoute: NewspapersNewspaperIdRenderRoute,
  NewspapersNewspaperIdIndexRoute: NewspapersNewspaperIdIndexRoute,
}

const NewspapersNewspaperIdRouteWithChildren =
  NewspapersNewspaperIdRoute._addFileChildren(
    NewspapersNewspaperIdRouteChildren,
  )

interface NewspapersRouteChildren {
  NewspapersNewspaperIdRoute: typeof NewspapersNewspaperIdRouteWithChildren
  NewspapersIndexRoute: typeof NewspapersIndexRoute
}

const NewspapersRouteChildren: NewspapersRouteChildren = {
  NewspapersNewspaperIdRoute: NewspapersNewspaperIdRouteWithChildren,
  NewspapersIndexRoute: NewspapersIndexRoute,
}

const NewspapersRouteWithChildren = NewspapersRoute._addFileChildren(
  NewspapersRouteChildren,
)

interface OrganizationRouteChildren {
  OrganizationLoginRoute: typeof OrganizationLoginRoute
  OrganizationSubscriptionRoute: typeof OrganizationSubscriptionRoute
  OrganizationIndexRoute: typeof OrganizationIndexRoute
}

const OrganizationRouteChildren: OrganizationRouteChildren = {
  OrganizationLoginRoute: OrganizationLoginRoute,
  OrganizationSubscriptionRoute: OrganizationSubscriptionRoute,
  OrganizationIndexRoute: OrganizationIndexRoute,
}

const OrganizationRouteWithChildren = OrganizationRoute._addFileChildren(
  OrganizationRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CartRoute: CartRoute,
  CategoriesRoute: CategoriesRouteWithChildren,
  CgcRoute: CgcRoute,
  CgvRoute: CgvRoute,
  ConfidentialiteRoute: ConfidentialiteRoute,
  ContactRoute: ContactRoute,
  CountriesRoute: CountriesRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  FaqRoute: FaqRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  MagazinesRoute: MagazinesRouteWithChildren,
  NewspapersRoute: NewspapersRouteWithChildren,
  OrganizationRoute: OrganizationRouteWithChildren,
  PartnershipRoute: PartnershipRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SupportRoute: SupportRoute,
  AgenciesAgencySlugRoute: AgenciesAgencySlugRoute,
  PaymentSuccessRoute: PaymentSuccessRoute,
  AgenciesIndexRoute: AgenciesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
